# base.yml - play to install a VM

- name: base.yml
  hosts: all

  roles:
    - { role: geerlingguy.git, become: yes, workspace: /root, git_install_from_source: true, git_install_from_source_force_update: true, git_version: "2.16.2", tags: ["git"] }
    - { role: ANXS.build-essential, become: yes, tags: ["build-essensial"] }
    - { role: RomanShestakov.ansible-role-common-tools, become: yes, tags: ["build-common"] }
    - { role: RomanShestakov.ansible-role-cmake, cmake_version: 3.8, cmake_minor_version: 2, tags: ["cmake"] }
    - { role: RomanShestakov.ansible-role-gcc, gcc_version: 4.9.4, binutils_version: 2.23, tags: ["gcc"] }
