# vm.yml - play to install a VM

- name: vm.yml
  hosts: all
  # connection: paramiko
  # vars:
  #   ansible_ssh_private_key_file: /path/to/private_key
  #   ansible_ssh_pass: passphrase_for_private_key

  # https://stackoverflow.com/questions/35616021/ansible-sudo-hangs-after-5-tasks
  pre_tasks:
    - name: Disable Fingerprint checking that may be enabled.  When enabled, causes SSH issues.
      command: authconfig --disablefingerprint --update

  roles:
    - { role: RomanShestakov.ansible-role-dotfiles, dotfiles_dest: "/home/vagrant" }
    - { role: RomanShestakov.ansible-role-tmux, become: yes, tags: ["tmux"] }
    - { role: RomanShestakov.ansible-role-emacs, become: yes, emacs_version: "emacs-27.1", tags: ["emacs"] }

  post_tasks:
    - name: .EMACS | get .emacs git repository
      become: yes
      become_user: vagrant
      git: repo={{ dot_emacs_repo_url }} dest="/home/vagrant/.emacs.d" accept_hostkey=yes force=yes

    - name: Set kernel.core_pattern in sysctl
      become: yes
      sysctl:
        name: kernel.core_pattern
        value: "/tmp/cores/core.%e.%p.%h.%"
        state: present
        reload: yes
